# Stage 1: Build the native executable
FROM quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-21 AS build
COPY --chown=quarkus:quarkus mvnw /code/mvnw
RUN chmod +x /code/mvnw
COPY --chown=quarkus:quarkus .mvn /code/.mvn
COPY --chown=quarkus:quarkus pom.xml /code/
USER quarkus
WORKDIR /code
RUN ./mvnw dependency:go-offline
COPY --chown=quarkus:quarkus src /code/src
COPY --chown=quarkus:quarkus web-panel /code/web-panel
# Build the native binary
RUN ./mvnw package -Dnative -Dquarkus.native.container-build=false -DskipTests

# Stage 2: Create the runtime image
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5
WORKDIR /work/
RUN microdnf install -y fontconfig freetype \
    && microdnf clean all \
    && chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --from=build --chown=1001:root /code/target/*-runner /work/application
COPY --from=build --chown=1001:root /code/target/*.so /work/

EXPOSE 8080
USER 1001

# Set the profile to prod and specify library path for AWT
ENV QUARKUS_PROFILE=prod
ENV LD_LIBRARY_PATH=/work

CMD ["./application", "-Dquarkus.http.host=0.0.0.0", "-Djava.awt.headless=true"]
