quarkus.quinoa.package-manager-install=true
quarkus.quinoa.package-manager-install.node-version=22.22.3
quarkus.quinoa.package-manager-install.pnpm-version=10.13.1
quarkus.quinoa.package-manager=pnpm
